[lf] implement proper image preview caching

diff --git a/scripts/lf-preview b/scripts/lf-preview
--- a/scripts/lf-preview
+++ b/scripts/lf-preview
@@ -1,55 +1,92 @@
 #!/bin/sh
+exec 2>&1
+
 # <https://github.com/gokcehan/lf/wiki/Previews#with-kitty-and-pistol>
 # <https://github.com/gokcehan/lf/issues/1537#issuecomment-1854956183>
 # <https://github.com/ranger/ranger/blob/08913377c968d39f11fa2d546aa8d53a99bb5e98/ranger/core/actions.py#L1054-L1140>
 
 file="$1" w="$2" h="$3" x="$4" y="$5"
 
-previewer="${DOTFILES_RANGER_PREVIEWER:-"$HOME/.config/ranger/scope.sh"}"
+image_id="$id"
+
+previewer="${DOTFILES_RANGER_PREVIEWER:-"${XDG_CONFIG_HOME:-${HOME}/.config}/ranger/scope.sh"}"
 if [ ! -x "$previewer" ]; then
   cat -- "$file"
   exit 0
 fi
 
-cachedir="${XDG_CACHE_HOME:-$HOME/.cache}/lf"
-mkdir -p -- "$cachedir"
+cachedir="${TMPDIR:-/tmp}/lf-${id}-preview-cache"
+mkdir -p -m 700 -- "$cachedir"  # hide the contents of the cache directory from other users
 
-cacheimg=
-if [ $# -gt 1 ] && sha="$(sha256sum -- "$file")"; then
-  cacheimg="${cachedir}/${sha%% *}"
-  trap 'rm -f -- "$cacheimg"' EXIT
+command_exists() {
+  command -v -- "$@" >/dev/null 2>&1
+}
+
+calculate_checksum() {
+  # b2sum is considerably faster than sha256sum or sha512sum, but is included
+  # only in GNU coreutils. sha512sum is more widely available, even from Busybox
+  # or Toybox, and is also noticeably faster than sha256sum.
+  if command_exists b2sum; then b2sum "$@"; else sha512sum "$@"; fi
+}
+
+enable_image_previews=False keep_cached_image=False cached_image=""
+if
+  command_exists kitten &&  # generate image previews only if we have the means of displaying them
+  [ -f "$file" ] &&  # try reading only regular files, avoid accessing pipes, sockets or devices
+  size="$(stat -c "%s" -- "$file" 2>/dev/null)" &&  # get the file size in bytes
+  # Avoid large files, as even computing a content hash for them can take considerable time
+  [ "$size" -le $(( 25 * 1000 * 1000 )) ] &&
+  checksum="$(calculate_checksum -- "$file" 2>/dev/null)"
+then
+  enable_image_previews=True
+  cached_image="${cachedir}/${checksum%% *}.png"
+  trap 'if [ "$keep_cached_image" = False ]; then rm -f -- "$cached_image"; fi' EXIT
 fi
 
 draw() {
   kitten icat --stdin no --transfer-mode memory --align left \
     --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
-  exit 1
 }
 
+draw_cached_image() {
+  if [ -s "$cached_image" ] && [ "$cached_image" -nt "$file" ]; then
+    if draw "$cached_image"; then
+      keep_cached_image=True
+      return 0
+    fi
+  fi
+  return 1
+}
+
+if draw_cached_image; then
+  exit 1
+fi
+
 # This mess of redirections is used to swap the stdout and stderr around, so
-# that the output of the subprocess to stderr is captured into a string, and
-# output to stdout goes straight to the real stdout. This is done so that errors
-# from `scope.sh` are displayed only if it fails to produce any sort of preview.
-exec 3>&1
-stderr="$("$previewer" "$file" "$w" "$h" "$cacheimg" "${cacheimg:+True}" 2>&1 1>&3 3>&-)"
+# that the stderr of the subprocess is captured into a string, and output to
+# stdout goes straight to the real stdout. This is done so that errors from
+# `scope.sh` are displayed only if it fails to produce any sort of preview.
+exec {pipe_to_stdout}>&1
+stderr="$(exec 2>&1 1>&$pipe_to_stdout {pipe_to_stdout}>&- -- \
+    "$previewer" "$file" "$w" "$h" "$cached_image" "$enable_image_previews")"
 code="$?"
-exec 3>&-
+exec {pipe_to_stdout}>&-
 
 # Meanings of exit codes of ranger's `scope.sh`:
 # 0 - success, a (colored) preview was printed to stdout
 # 1 - there was an error, no preview could be generated
-# 2 - no preview was generated, the file should be displayed as plain text
+# 2 - no preview was generated, the contents of the file should be displayed as plain text
 # 3 - success, same as 0, but there is no need to reload the preview when screen width changes
 # 4 - same as 3, but don't reload when screen height chanes
 # 5 - same as 3, but don't ever reload, the preview can be cached indefinitely
-# 6 - a thumbnail image was generated and written into $cacheimg, display it
+# 6 - a thumbnail image was generated and written to ${cached_image}, display it
 # 7 - no preview was generated, display the file itself as an image
 # <https://github.com/ranger/ranger/blob/08913377c968d39f11fa2d546aa8d53a99bb5e98/ranger/data/scope.sh#L18-L28>
 case "$code" in
-  (1) printf '%s\n' "$stderr";;
+  (1) [ -n "$stderr" ] && printf '%s\n' "$stderr";;
   (2) cat -- "$1";;
-  (6) [ "$cacheimg" -nt "$file" ] && draw "$cacheimg";;
-  (7) draw "$file";;
+  (6) draw_cached_image && exit 1;;
+  (7) draw "$file" && exit 1;;
 esac
 
 exit 0
